podhelper_path = File.expand_path(File.join('Flutter', 'podhelper.rb'), __dir__)
require podhelper_path

platform :ios, '13.0'
install! 'cocoapods', :deterministic_uuids => false

target 'Runner' do
  use_frameworks! :linkage => :static
  use_modular_headers!
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      # إعدادات لضمان التوافق مع معالج M2 و Xcode الحديث
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
      config.build_settings['ENABLE_BITCODE'] = 'NO'
      config.build_settings['PRODUCT_BUNDLE_IDENTIFIER'] = 'com.mostbeautiful.app'
      
      # هذا السطر يحل مشكلة الخطأ -G وتعارضات المعالج
      config.build_settings['DEBUG_INFORMATION_FORMAT'] = 'dwarf'
    end
  end
end