# 1. السطر الأهم: استدعاء ملف مساعدة فلاتر (هذا ما كان ينقصنا)
link_code = File.join(File.dirname(File.realpath(__FILE__)), 'Flutter', 'podhelper.rb')
load link_code

platform :ios, '13.0'

install! 'cocoapods', :deterministic_uuids => false

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  # 2. الآن سيعرف الماك معنى هذا الأمر
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end