# الإصدار 13 لضمان أعلى توافق مع مكتبات فلاتر الحديثة
platform :ios, '13.0'

# تعطيل التحقق من التوقيع للبناء السحابي
install! 'cocoapods', :deterministic_uuids => false

target 'Runner' do
  # هذا السطر هو الحل السحري لمشكلة "Module not found"
  use_frameworks! :linkage => :static
  use_modular_headers!

  # سنطلب من الماك تحميل مكتبات فايربيز الأساسية فقط
  # الماك سيعرف تلقائياً بقية التوابع
  pod 'Firebase/Firestore'
  pod 'Firebase/Auth'
  pod 'Firebase/Core'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      # إعدادات لضمان استقرار البناء
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
      config.build_settings['ENABLE_BITCODE'] = 'NO'
      config.build_settings['PRODUCT_BUNDLE_IDENTIFIER'] = 'com.mostbeautiful.app'
      
      # سطر إضافي لحل مشكلة التوافق مع Xcode الحديث
      config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
    end
  end
end